### ISSUE TITLE
Bugg, can't find the cards after update, look like the app i broken.

### ISSUE THREAD

**Issue by Westlunds** [fredrikjohnsson/temperaturnu#8]
Bugg, can't find the cards after update, looks like the app is broken. Br /Fredrik

**Comment by fredrikjohnsson** [comment]
Which version of the app and Homey are you running?

**Comment by Westlunds** [comment]
Hi,  the Homey has version 2.3 and the phone got 2.5.1.335. Everything worked before the update. I have a Homey Pro.

Br

/Fredrik

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________

**Comment by fredrikjohnsson** [comment]
Are you running the latest version (1.1.1) of the Temperatur.nu app? At the moment I have massive problems with my Homey being offline and unreachable most of the time, so troubleshooting this problem at my end will be difficult.

**Comment by Westlunds** [comment]
Yes, om using 1.1.1.

Br

/Fredrik

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________

**Comment by fredrikjohnsson** [comment]
I could actually access my Homey now for a few minutes and I have no issue with flows and can find the cards. I would recommend the uninstall and reinstall temperatur.nu app.

**Comment by Westlunds** [comment]
I have unistalled and installed it again and rebooted it twice :-(

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________

**Comment by Westlunds** [comment]
51987592-ae97-4579-b8e1-a712c42cfc32

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________

**Comment by Westlunds** [comment]
Hi again, i have checked and the app works but the when card is missing temeratur.nu but the then card can find it temperatur.nu

Br

/Fredrik

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________

**Comment by fredrikjohnsson** [comment]
Actually, you should not find temperatur.nu as a When-card, you should look for your temperatur.nu device name in the list. So, it basically means that you have to create a device collecting data from temperatur.nu to be able to get access to the When-card.

**Comment by Westlunds** [comment]
Thanks för the help, the device was gone, probably after update but after i added it again everything work as it should

Br

/Fredrik

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________

**Comment by fredrikjohnsson** [comment]
Perfect!
